
#define _ERR_UPLOAD_LOG_RESTART				true
#define _ERR_UPLOAD_LOG_DONT_RESTART		false
#define _ERR_UPLOAD_LOG_SAVE_CONFIG			true
#define _ERR_UPLOAD_LOG_DONT_SAVE_CONFIG	false


#define _ERR_NOERROR					0

#define _ERR_SENSOR				       (-70)
#define _ERR_SENSOR_READ	           (_ERR_SENSOR - 1)
#define _ERR_SENSOR_GPS_POOR_SIGNAL    (_ERR_SENSOR_READ - 1)
#define _ERR_SENSOR_GPS_POOR_PRECISION (_ERR_SENSOR_GPS_POOR_SIGNAL - 1)

#define _ERR_NOT_CONTROLED_RESTART     (_ERR_SENSOR - 10)